server:
  port: 8222

eureka:
  client:
    register-with-eureka: false

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user
          uri: http://localhost:8081
          predicates:
<<<<<<< HEAD
            - Path=/api/auth/**, /api/users/**
=======
            - Path=/api/auth/** , /api/users/**
>>>>>>> d27a815fd657b276f6daa433f001162d68af3607

        - id: lostItems
          uri: http://localhost:8082
          predicates:
            - Path=/api/LostFound/**
          filters:
            - PreserveHostHeader
#            - AddRequestHeader=Authorization, #{token} # Optional: you might want to replace this with a value

management:
  server:
    port: 8222
  tracing:
    sampling:
      probability: 1.0
