server:
  port: 8081

spring:
  cloud:
    compatibility-verifier:
      enabled: false
      application:
        name: user-service
      datasource:
        url: jdbc:mysql://localhost:3306/lost&found
        username: root
        password: 12345678
        driver-class-name: com.mysql.cj.jdbc.Driver
      jpa:
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
          ddl-auto: update
        show-sql: true
      mvc:
        static-path-pattern: /static/**

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka
